export const NAV_CLOSE = 'NAV_CLOSE';
export const NAV_OPEN = 'NAV_OPEN';

export const CHANGE_COURSE_LANGUAGE = 'CHANGE_COURSE_LANGUAGE';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST_BY_TITLE = 'FETCH_POST_BY_TITLE';